#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# Der Wizard lebt von Rückfragen. Ohne Terminal an stdin liefert jedes `read`
# sofort EOF, und das Skript rauscht mit leeren Antworten durch alle Stufen -
# im schlimmsten Fall bis zu einem Deployment, das niemand bestätigt hat.
# Das passiert unter anderem beim `!`-Prefix in Claude Code und in Pipes.
# Wenn ein steuerndes Terminal erreichbar ist, holen wir es uns zurück.
if [[ ! -t 0 ]]; then
  if [[ -r /dev/tty ]] && exec </dev/tty 2>/dev/null && [[ -t 0 ]]; then
    :
  else
    printf 'Dieses Skript braucht ein Terminal an stdin.\n' >&2
    printf 'In einem normalen Terminal starten, nicht über eine Pipe oder\n' >&2
    printf 'den !-Prefix in Claude Code:\n\n' >&2
    printf '  %s\n\n' "$0" >&2
    exit 1
  fi
fi

# Feste Werte dieser Installation. Quelle: docs/plans/2026-08-08-dokploy-app-from-ghcr.md
PANEL="${DOKPLOY_URL:-https://manage.weissteiner-automation.com}"
APP="${DOKPLOY_APPLICATION_ID:-7SegzhqX2qLM3NY75qGPR}"
DOMAIN="${WA_DOMAIN:-weissteiner-automation.com}"
VPS_IP="${WA_VPS_IP:-186.240.157.55}"
VOLUME_NAME="wa-website-image-cache"
MOUNT_PATH="/app/.next/cache/images"

# Der Cache-Test benutzt Breiten, die die Webseite selbst nie anfragt (das Hero
# rendert mit sizes="100vw" nur deviceSizes). Nur so ist "kalt" wirklich kalt.
# q muss 75 sein - images.qualities lässt in Next 16 nichts anderes zu.
IMG="url=%2Fgruenten.jpg&q=75"

# api METHOD PATH [JSON] - ruft die Dokploy-API auf, Antwort nach $API_BODY.
# Setzt $API_CODE. Bricht nicht ab; die Stages werten selbst aus.
API_BODY=""
API_CODE=""
api() {
  local method="$1" path="$2" body="${3:-}" tmp
  tmp=$(mktemp)
  if [[ -n "$body" ]]; then
    API_CODE=$(curl -sS --max-time 60 -o "$tmp" -w '%{http_code}' -X "$method" \
      "$PANEL/api/$path" -H "x-api-key: $DOKPLOY_API_KEY" \
      -H 'Content-Type: application/json' -d "$body" || echo 000)
  else
    API_CODE=$(curl -sS --max-time 60 -o "$tmp" -w '%{http_code}' -X "$method" \
      "$PANEL/api/$path" -H "x-api-key: $DOKPLOY_API_KEY" || echo 000)
  fi
  API_BODY=$(cat "$tmp"); rm -f "$tmp"
}

# fetch_img WIDTH - ruft eine Bildvariante über die Server-Adresse ab, am DNS
# vorbei (--resolve) und ohne Zertifikatsprüfung (-k). Beides nötig, solange
# die Domain noch auf das alte Hosting zeigt (#25). Gibt "CODE SEKUNDEN" aus.
fetch_img() {
  curl -sSk --max-time 60 --resolve "$DOMAIN:443:$VPS_IP" -o /dev/null \
    -w '%{http_code} %{time_total}' "https://$DOMAIN/_next/image?$IMG&w=$1" \
    2>/dev/null || echo "000 0"
}

# faster_than A B - wahr, wenn Zeit A weniger als die Hälfte von Zeit B ist.
# Verhältnis statt fester Schwelle, weil die Netzlaufzeit den Messwert
# dominiert und von der Leitung abhängt, nicht von der Serverlast.
faster_than() { awk -v a="$1" -v b="$2" 'BEGIN { exit !(a * 2 < b) }'; }

banner "Dokploy: Volume für den Image-Optimizer-Cache (#24)"

# ──────────────────────────────────────────────────────────────────────────
stage "Zugang und Vorbedingung"
say "Das Volume darf erst hängen, wenn das Image den Ordner $MOUNT_PATH"
say "bereits enthält und er nextjs gehört. Andernfalls legt Docker den"
say "Mount-Punkt als root an, das Volume merkt sich das, und der Optimizer"
say "rechnet stumm bei jedem Abruf neu."
printf '\n'
command -v jq >/dev/null 2>&1 || { warn "jq fehlt - \"brew install jq\", dann erneut starten."; exit 1; }
if [[ -z "${DOKPLOY_API_KEY:-}" ]]; then
  step "Dokploy-Panel → oben rechts Profil → API/CLI → Key kopieren."
  ask_secret DOKPLOY_API_KEY "Dokploy-API-Key:"
else
  note "DOKPLOY_API_KEY aus der Umgebung übernommen."
fi
[[ -n "${DOKPLOY_API_KEY:-}" ]] || { warn "Ohne API-Key geht es nicht."; exit 1; }

api GET "application.one?applicationId=$APP"
if [[ "$API_CODE" != "200" ]]; then
  warn "application.one antwortete mit HTTP $API_CODE - Key oder Panel-URL prüfen."
  printf '  %s\n' "$API_BODY"; exit 1
fi
DEPLOYED_IMAGE=$(printf '%s' "$API_BODY" | jq -r '[.. | objects | select(has("dockerImage"))] | .[0].dockerImage // "?"')
printf '\n'; note "Aktuell eingetragenes Image: $DEPLOYED_IMAGE"
printf '\n'
warn "Dieses Image muss aus einem Commit stammen, der den Dockerfile-Schritt"
warn "\"mkdir -p $MOUNT_PATH\" enthält - also aus dem gemergten PR zu #24."
confirm "Ist der PR zu #24 auf main gemergt und dieses Image daraus gebaut?" \
  || { printf '\n'; say "Dann zuerst mergen und den Build abwarten. Danach dieses Skript erneut starten."; exit 0; }

# ──────────────────────────────────────────────────────────────────────────
stage "Volume in Dokploy anlegen"
say "Volume Mount, kein Bind Mount: ein von Docker verwaltetes Volume ist"
say "sicherbar und umziehbar, ohne dass ein Hostpfad im Spiel ist."
printf '\n'
open_url "$PANEL/dashboard/project/AVTwc57NrDC3ixEIQKqse"
step "Anwendung \"wa-website\" öffnen → Reiter Advanced → Abschnitt Volumes."
step "Add Volume → Mount Type: Volume Mount."
step "Volume Name:  $VOLUME_NAME"
step "Mount Path:   $MOUNT_PATH"
step "Create klicken. Noch NICHT deployen - das macht die nächste Stage."
printf '\n'
pause "Angelegt? Enter zum Prüfen."

api GET "application.one?applicationId=$APP"
MOUNT_OK=$(printf '%s' "$API_BODY" | jq -r --arg p "$MOUNT_PATH" --arg v "$VOLUME_NAME" \
  '[.. | objects | select(.mountPath? == $p and .volumeName? == $v)] | length')
if [[ "${MOUNT_OK:-0}" -lt 1 ]]; then
  warn "Kein Volume Mount mit $MOUNT_PATH / $VOLUME_NAME gefunden."
  note "Gefundene Mounts:"
  printf '%s' "$API_BODY" | jq -r '[.. | objects | select(has("mountPath"))] | .[] | "  - \(.type // "?") \(.volumeName // .hostPath // "?") → \(.mountPath)"' 2>/dev/null || true
  exit 1
fi
printf '  %s✓%s Volume Mount eingetragen.\n' "$GREEN" "$RESET"

# ──────────────────────────────────────────────────────────────────────────
stage "Deployen, damit das Volume greift"
say "Ein Mount wird erst beim Neuerzeugen des Swarm-Service wirksam."
say "Der laufende Container wird dabei ersetzt (start-first, kein Loch)."
printf '\n'
confirm "Jetzt deployen?" || { warn "Abgebrochen. Ohne Deploy hängt das Volume nicht."; exit 0; }

DEPLOY_TITLE="Wizard image-cache-volume $$"
api POST "application.deploy" "$(jq -n --arg id "$APP" --arg t "$DEPLOY_TITLE" \
  '{applicationId: $id, title: $t, description: "Volume für den Image-Optimizer-Cache (#24)"}')"
if [[ "$API_CODE" != "200" ]]; then
  warn "application.deploy antwortete mit HTTP $API_CODE:"; printf '  %s\n' "$API_BODY"; exit 1
fi
printf '  %s↻%s Deployment ausgelöst, warte auf Abschluss ...\n' "$BLUE" "$RESET"

DEPLOY_STATUS=pending
for _ in $(seq 1 60); do
  sleep 10
  api GET "deployment.all?applicationId=$APP"
  [[ "$API_CODE" == "200" ]] || { note "  HTTP $API_CODE, erneuter Versuch"; continue; }
  DEPLOY_STATUS=$(printf '%s' "$API_BODY" | jq -r --arg t "$DEPLOY_TITLE" \
    '[.. | objects | select(.title? == $t and has("status"))] | .[0].status // "pending"' 2>/dev/null) || DEPLOY_STATUS=pending
  printf '  %sStatus: %s%s\n' "$DIM" "$DEPLOY_STATUS" "$RESET"
  [[ "$DEPLOY_STATUS" == "done" ]] && break
  if [[ "$DEPLOY_STATUS" == "error" || "$DEPLOY_STATUS" == "cancelled" ]]; then
    warn "Deployment fehlgeschlagen - Logs im Dokploy-Panel."; exit 1
  fi
done
[[ "$DEPLOY_STATUS" == "done" ]] || { warn "Deployment nach 10 Minuten nicht abgeschlossen."; exit 1; }
printf '  %s✓%s Deployment abgeschlossen.\n' "$GREEN" "$RESET"

# ──────────────────────────────────────────────────────────────────────────
stage "Schreibrechte im Volume prüfen"
say "Zwei Abrufe derselben ungenutzten Bildvariante. Der zweite muss deutlich"
say "schneller sein - sonst konnte der erste nichts ablegen, und das heißt:"
say "der Mount-Punkt gehört root."
printf '\n'
read -r COLD_CODE COLD_T <<<"$(fetch_img 384)"
printf '  1. Abruf (w=384): HTTP %s, %ss\n' "$COLD_CODE" "$COLD_T"
read -r WARM_CODE WARM_T <<<"$(fetch_img 384)"
printf '  2. Abruf (w=384): HTTP %s, %ss\n' "$WARM_CODE" "$WARM_T"
printf '\n'
if [[ "$COLD_CODE" != "200" || "$WARM_CODE" != "200" ]]; then
  warn "Kein HTTP 200 - erst das klären, die Messung sagt sonst nichts."; exit 1
fi
if faster_than "$WARM_T" "$COLD_T"; then
  printf '  %s✓%s Der Optimizer schreibt und liest im Volume.\n' "$GREEN" "$RESET"
else
  warn "Kein Unterschied messbar. Wahrscheinlichste Ursache: das Volume wurde"
  warn "angelegt, bevor das Image den Ordner enthielt - dann gehört es root."
  note "Reparatur: Volume in Dokploy entfernen, im Panel unter"
  note "Docker → Volumes das Volume \"$VOLUME_NAME\" löschen, Stage 2 wiederholen."
  exit 1
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Persistenz über ein Deployment beweisen"
say "Noch ein Deployment, danach zwei Messungen im selben Zeitfenster:"
say "die zuvor gecachte Variante (w=384) gegen eine nie abgerufene (w=256)."
say "Nur der Vergleich beider trennt einen überlebenden Cache von einer"
say "zufällig schnellen Leitung."
printf '\n'
confirm "Zweites Deployment auslösen?" || { warn "Ohne das ist die Persistenz nicht belegt."; exit 0; }

DEPLOY_TITLE="Wizard image-cache-proof $$"
api POST "application.deploy" "$(jq -n --arg id "$APP" --arg t "$DEPLOY_TITLE" \
  '{applicationId: $id, title: $t, description: "Persistenznachweis Image-Cache (#24)"}')"
[[ "$API_CODE" == "200" ]] || { warn "application.deploy: HTTP $API_CODE"; printf '  %s\n' "$API_BODY"; exit 1; }
DEPLOY_STATUS=pending
for _ in $(seq 1 60); do
  sleep 10
  api GET "deployment.all?applicationId=$APP"
  [[ "$API_CODE" == "200" ]] || continue
  DEPLOY_STATUS=$(printf '%s' "$API_BODY" | jq -r --arg t "$DEPLOY_TITLE" \
    '[.. | objects | select(.title? == $t and has("status"))] | .[0].status // "pending"' 2>/dev/null) || DEPLOY_STATUS=pending
  printf '  %sStatus: %s%s\n' "$DIM" "$DEPLOY_STATUS" "$RESET"
  [[ "$DEPLOY_STATUS" == "done" ]] && break
  if [[ "$DEPLOY_STATUS" == "error" || "$DEPLOY_STATUS" == "cancelled" ]]; then
    warn "Deployment fehlgeschlagen - Logs im Dokploy-Panel."; exit 1
  fi
done
[[ "$DEPLOY_STATUS" == "done" ]] || { warn "Deployment nach 10 Minuten nicht abgeschlossen."; exit 1; }

printf '\n'
read -r KEPT_CODE KEPT_T <<<"$(fetch_img 384)"
printf '  gecachte Variante  (w=384): HTTP %s, %ss\n' "$KEPT_CODE" "$KEPT_T"
read -r CTRL_CODE CTRL_T <<<"$(fetch_img 256)"
printf '  Kontrolle, kalt    (w=256): HTTP %s, %ss\n' "$CTRL_CODE" "$CTRL_T"
printf '\n'
if [[ "$KEPT_CODE" != "200" || "$CTRL_CODE" != "200" ]]; then
  warn "Kein HTTP 200 - Messung wertlos."; exit 1
fi
if faster_than "$KEPT_T" "$CTRL_T"; then
  printf '  %s✓%s Der Cache hat das Deployment überlebt.\n' "$GREEN" "$RESET"
else
  warn "Die zuvor gecachte Variante war nicht schneller als eine kalte."
  warn "Der Cache überlebt das Deployment also nicht."
  note "Prüfen: hängt das Volume wirklich an $MOUNT_PATH (Stage 2), und wurde"
  note "es angelegt, nachdem das Image den Ordner mitbrachte?"
  exit 1
fi

finish
note "Volume $VOLUME_NAME an $MOUNT_PATH - reiner Cache."
note "Löschen ist gefahrlos: es kostet einmalig Rechenzeit, keine Daten."
