#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s Stufen%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  Du bedienst den Browser, dieses Skript sagt dir genau was zu tun ist\n' "$DIM"
  printf '  und prüft jeden Schritt nach. Jederzeit mit Ctrl-C abbrechen und später\n'
  printf '  neu starten - nichts davon ist unumkehrbar.%s\n' "$RESET"
  pause "Bereit? Enter zum Starten."
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "Kein Browser gestartet - Adresse selbst öffnen: $url"; fi
  } >/dev/null 2>&1 || warn "Kein Browser gestartet - Adresse selbst öffnen: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Enter zum Fortfahren}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "GitHub-Secret $name übersprungen - gh nicht bereit, später setzen"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "GitHub-Variable $name übersprungen - gh nicht bereit, später setzen"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Fertig%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "Von Hand nachzuholen:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# Der Wizard lebt von Rückfragen. Ohne Terminal an stdin liefert jedes `read`
# sofort EOF, und das Skript rauscht mit leeren Antworten durch alle Stufen -
# im schlimmsten Fall bis zu einem Deployment, das niemand bestätigt hat.
# Das passiert unter anderem beim `!`-Prefix in Claude Code und in Pipes.
# Wenn ein steuerndes Terminal erreichbar ist, holen wir es uns zurück.
if [[ ! -t 0 ]]; then
  # Die Klammern begrenzen die Umleitung von stderr auf diesen einen Versuch -
  # ohne sie wäre stderr für den Rest des Laufs auf /dev/null gerichtet und
  # jede spätere Fehlermeldung verschwunden. Die Umleitung von stdin durch
  # exec bleibt dagegen bestehen, genau wie gewollt.
  if { exec </dev/tty; } 2>/dev/null && [[ -t 0 ]]; then
    :
  else
    printf 'Dieses Skript braucht ein Terminal an stdin.\n' >&2
    printf 'In einem normalen Terminal starten, nicht über eine Pipe oder\n' >&2
    printf 'den !-Prefix in Claude Code:\n\n' >&2
    printf '  %s\n\n' "$0" >&2
    exit 1
  fi
fi

# Feste Werte dieser Installation. Quelle: docs/plans/2026-08-08-dokploy-app-from-ghcr.md
PANEL="${DOKPLOY_URL:-https://manage.weissteiner-automation.com}"
APP="${DOKPLOY_APPLICATION_ID:-7SegzhqX2qLM3NY75qGPR}"
DOMAIN="${WA_DOMAIN:-weissteiner-automation.com}"
VPS_IP="${WA_VPS_IP:-186.240.157.55}"
VOLUME_NAME="wa-website-image-cache"
MOUNT_PATH="/app/.next/cache/images"

# Der Cache-Test benutzt Breiten, die die Webseite selbst nie anfragt (das Hero
# rendert mit sizes="100vw" nur deviceSizes). Nur so ist der erste Abruf
# wirklich ein Fehltreffer.
# q muss 75 sein - images.qualities lässt in Next 16 nichts anderes zu.
IMG="url=%2Fgruenten.jpg&q=75"
PROBE_WIDTH="${PROBE_WIDTH:-128}"   # die Variante, die das Deployment überleben soll
CONTROL_WIDTH="${CONTROL_WIDTH:-64}" # Gegenprobe, wird erst nach dem Deploy geholt

# api METHOD PATH [JSON] - ruft die Dokploy-API auf, Antwort nach $API_BODY.
# Setzt $API_CODE. Bricht nicht ab; die Stages werten selbst aus.
API_BODY=""
API_CODE=""
api() {
  local method="$1" path="$2" body="${3:-}" tmp
  tmp=$(mktemp)
  if [[ -n "$body" ]]; then
    API_CODE=$(curl -sS --max-time 60 -o "$tmp" -w '%{http_code}' -X "$method" \
      "$PANEL/api/$path" -H "x-api-key: $DOKPLOY_API_KEY" \
      -H 'Content-Type: application/json' -d "$body" || echo 000)
  else
    API_CODE=$(curl -sS --max-time 60 -o "$tmp" -w '%{http_code}' -X "$method" \
      "$PANEL/api/$path" -H "x-api-key: $DOKPLOY_API_KEY" || echo 000)
  fi
  API_BODY=$(cat "$tmp"); rm -f "$tmp"
}

# deploy_and_wait TITEL BESCHREIBUNG - stößt ein Deployment an und wartet, bis
# der Datensatz mit genau diesem Titel "done" meldet. Dokploy schreibt den
# mitgeschickten title unverändert in den Datensatz; daran wird der eigene Lauf
# wiedergefunden. Nicht an applicationStatus: der springt binnen Sekunden auf
# "done", während Swarm noch rollt.
#
# Die Abbruchbedingungen sind dieselben wie in .github/workflows/deploy.yml und
# aus demselben Grund: 401/403/404 werden durch Warten nicht besser, und ein
# Datensatz, der nach zwei Minuten nicht existiert, heißt, dass die Annahme über
# den Titel nicht mehr stimmt. Beides soll sofort scheitern statt nach zehn
# Minuten als irreführender Timeout.
deploy_and_wait() {
  local title="$1" description="$2" status=pending missing=0
  api POST "application.deploy" "$(jq -n --arg id "$APP" --arg t "$title" --arg d "$description" \
    '{applicationId: $id, title: $t, description: $d}')"
  if [[ "$API_CODE" != "200" ]]; then
    warn "application.deploy antwortete mit HTTP $API_CODE:"; printf '  %s\n' "$API_BODY"; exit 1
  fi
  printf '  %s↻%s Deployment ausgelöst, warte auf Abschluss ...\n' "$BLUE" "$RESET"

  local _
  for _ in $(seq 1 60); do
    sleep 10
    api GET "deployment.all?applicationId=$APP"
    case "$API_CODE" in
      200) ;;
      401|403|404)
        warn "deployment.all antwortete mit HTTP $API_CODE - kein Wiederholungsfall:"
        printf '  %s\n' "$API_BODY"; exit 1 ;;
      *) note "  HTTP $API_CODE, erneuter Versuch"; continue ;;
    esac
    status=$(printf '%s' "$API_BODY" | jq -r --arg t "$title" \
      '[.. | objects | select(.title? == $t and has("status"))] | .[0].status // "pending"' \
      2>/dev/null) || status=pending
    printf '  %sStatus: %s%s\n' "$DIM" "$status" "$RESET"
    case "$status" in
      done) printf '  %s✓%s Deployment abgeschlossen.\n' "$GREEN" "$RESET"; return 0 ;;
      error|cancelled) warn "Deployment fehlgeschlagen - Logs im Dokploy-Panel."; exit 1 ;;
      pending)
        missing=$((missing + 1))
        if [[ "$missing" -ge 12 ]]; then
          warn "Kein Deployment mit dem Titel \"$title\" gefunden."
          warn "Es läuft womöglich trotzdem - im Dokploy-Panel nachsehen."
          exit 1
        fi ;;
    esac
  done
  warn "Deployment nach 10 Minuten weder done noch error - Abbruch."
  exit 1
}

# probe WIDTH - ruft eine Bildvariante über die Server-Adresse ab, am DNS vorbei
# (--resolve) und ohne Zertifikatsprüfung (-k). Beides nötig, solange die Domain
# noch auf das alte Hosting zeigt (#25). Gibt "HTTPCODE CACHESTATUS" aus.
#
# Ausgewertet wird der Header x-nextjs-cache (HIT/MISS/STALE), nicht die Dauer.
# Zeitmessung wäre hier wertlos: seit die Quelldatei 569 KB statt 14 MB hat,
# liegt die Transkodierzeit unter der Netzlaufzeit - gemessen an der VPS waren
# Treffer und Fehltreffer beide bei rund 0,1 s. Der Header sagt es dagegen
# direkt und ohne Schwellenwert.
probe() {
  local head code status
  # Accept mitschicken: der MIME-Typ geht in den Cache-Schlüssel ein. Ohne den
  # Header prüfte der Wizard eine JPEG-Variante, die kein Browser je anfragt -
  # gemessen würde ein Cache, den niemand benutzt.
  head=$(curl -sSkI --max-time 60 --resolve "$DOMAIN:443:$VPS_IP" \
    -H 'Accept: image/webp,image/*,*/*' \
    "https://$DOMAIN/_next/image?$IMG&w=$1" 2>/dev/null | tr -d '\r') \
    || { echo "000 UNREACHABLE"; return; }
  # tail -n1 statt head: bei einer Weiterleitung zählt die letzte Antwort.
  code=$(printf '%s\n' "$head" | sed -n 's|^HTTP/[0-9.]* \([0-9][0-9][0-9]\).*|\1|p' | tail -n1)
  status=$(printf '%s\n' "$head" | sed -n 's/^[Xx]-[Nn]ext[Jj][Ss]-[Cc]ache: *//p' | tail -n1)
  echo "${code:-000} ${status:-KEIN_HEADER}"
}

banner "Dokploy: Volume für den Image-Optimizer-Cache (#24)"

# ──────────────────────────────────────────────────────────────────────────
stage "Zugang und Vorbedingung"
say "Das Volume darf erst hängen, wenn das Image den Ordner $MOUNT_PATH"
say "bereits enthält und er nextjs gehört. Andernfalls legt Docker den"
say "Mount-Punkt als root an, das Volume merkt sich das, und der Optimizer"
say "rechnet stumm bei jedem Abruf neu."
printf '\n'
command -v jq >/dev/null 2>&1 || { warn "jq fehlt - \"brew install jq\", dann erneut starten."; exit 1; }
if [[ -z "${DOKPLOY_API_KEY:-}" ]]; then
  step "Dokploy-Panel → oben rechts Profil → API/CLI → Key kopieren."
  ask_secret DOKPLOY_API_KEY "Dokploy-API-Key:"
else
  note "DOKPLOY_API_KEY aus der Umgebung übernommen."
fi
[[ -n "${DOKPLOY_API_KEY:-}" ]] || { warn "Ohne API-Key geht es nicht."; exit 1; }

api GET "application.one?applicationId=$APP"
if [[ "$API_CODE" != "200" ]]; then
  warn "application.one antwortete mit HTTP $API_CODE - Key oder Panel-URL prüfen."
  printf '  %s\n' "$API_BODY"; exit 1
fi
DEPLOYED_IMAGE=$(printf '%s' "$API_BODY" | jq -r '[.. | objects | select(has("dockerImage"))] | .[0].dockerImage // "?"' 2>/dev/null) || DEPLOYED_IMAGE="?"
printf '\n'; note "Aktuell eingetragenes Image: $DEPLOYED_IMAGE"
printf '\n'
warn "Dieses Image muss aus einem Commit stammen, der den Dockerfile-Schritt"
warn "\"mkdir -p $MOUNT_PATH\" enthält - also aus dem gemergten PR zu #24."
confirm "Ist der PR zu #24 auf main gemergt und dieses Image daraus gebaut?" \
  || { printf '\n'; say "Dann zuerst mergen und den Build abwarten. Danach dieses Skript erneut starten."; exit 0; }

# ──────────────────────────────────────────────────────────────────────────
stage "Volume in Dokploy anlegen"
say "Volume Mount, kein Bind Mount: ein von Docker verwaltetes Volume ist"
say "sicherbar und umziehbar, ohne dass ein Hostpfad im Spiel ist."
printf '\n'
open_url "$PANEL/dashboard/project/AVTwc57NrDC3ixEIQKqse"
step "Anwendung \"wa-website\" öffnen → Reiter Advanced → Abschnitt Volumes."
step "Add Volume → Mount Type: Volume Mount."
step "Volume Name:  $VOLUME_NAME"
step "Mount Path:   $MOUNT_PATH"
step "Create klicken. Noch NICHT deployen - das macht die nächste Stage."
printf '\n'
pause "Angelegt? Enter zum Prüfen."

api GET "application.one?applicationId=$APP"
if [[ "$API_CODE" != "200" ]]; then
  warn "application.one antwortete mit HTTP $API_CODE:"; printf '  %s\n' "$API_BODY"; exit 1
fi
# jq scheitert, wenn ein Proxy mit HTTP 200 und HTML antwortet. Unter set -e
# stürbe das Skript hier wortlos - deshalb abfangen und als "nicht gefunden"
# behandeln, dann greift die Diagnose unten.
MOUNT_OK=$(printf '%s' "$API_BODY" | jq -r --arg p "$MOUNT_PATH" --arg v "$VOLUME_NAME" \
  '[.. | objects | select(.mountPath? == $p and .volumeName? == $v)] | length' 2>/dev/null) || MOUNT_OK=0
if [[ "${MOUNT_OK:-0}" -lt 1 ]]; then
  warn "Kein Volume Mount mit $MOUNT_PATH / $VOLUME_NAME gefunden."
  note "Gefundene Mounts:"
  printf '%s' "$API_BODY" | jq -r '[.. | objects | select(has("mountPath"))] | .[] | "  - \(.type // "?") \(.volumeName // .hostPath // "?") → \(.mountPath)"' 2>/dev/null || true
  exit 1
fi
printf '  %s✓%s Volume Mount eingetragen.\n' "$GREEN" "$RESET"

# ──────────────────────────────────────────────────────────────────────────
stage "Deployen, damit das Volume greift"
say "Ein Mount wird erst beim Neuerzeugen des Swarm-Service wirksam."
say "Der laufende Container wird dabei ersetzt (start-first, kein Loch)."
printf '\n'
confirm "Jetzt deployen?" || { warn "Abgebrochen. Ohne Deploy hängt das Volume nicht."; exit 0; }

deploy_and_wait "Wizard image-cache-volume $$" "Volume für den Image-Optimizer-Cache (#24)"

# ──────────────────────────────────────────────────────────────────────────
stage "Schreibrechte im Volume prüfen"
say "Zwei Abrufe derselben ungenutzten Bildvariante. Der erste muss MISS"
say "melden, der zweite HIT. Bleibt es beim zweiten bei MISS, konnte der"
say "Optimizer nichts ablegen - dann gehört der Mount-Punkt root."
printf '\n'
read -r FIRST_CODE FIRST_STATUS <<<"$(probe "$PROBE_WIDTH")"
printf '  1. Abruf (w=%s): HTTP %s, x-nextjs-cache: %s\n' "$PROBE_WIDTH" "$FIRST_CODE" "$FIRST_STATUS"
read -r SECOND_CODE SECOND_STATUS <<<"$(probe "$PROBE_WIDTH")"
printf '  2. Abruf (w=%s): HTTP %s, x-nextjs-cache: %s\n' "$PROBE_WIDTH" "$SECOND_CODE" "$SECOND_STATUS"
printf '\n'
if [[ "$FIRST_CODE" != "200" || "$SECOND_CODE" != "200" ]]; then
  warn "Kein HTTP 200 - erst das klären, die Prüfung sagt sonst nichts."; exit 1
fi
if [[ "$FIRST_STATUS" == "KEIN_HEADER" ]]; then
  warn "Antwort ohne x-nextjs-cache. Entweder liefert nicht der Optimizer die"
  warn "Antwort, oder eine Zwischenschicht entfernt den Header."
  exit 1
fi
if [[ "$FIRST_STATUS" != "MISS" ]]; then
  warn "Erster Abruf war schon \"$FIRST_STATUS\" - die Variante w=$PROBE_WIDTH liegt"
  warn "bereits im Cache. Damit prüft diese Stufe nichts."
  note "Mit einer unbenutzten Breite erneut starten, z. B.:"
  note "  PROBE_WIDTH=32 CONTROL_WIDTH=48 $0"
  exit 1
fi
if [[ "$SECOND_STATUS" == "HIT" ]]; then
  printf '  %s✓%s Der Optimizer schreibt und liest im Volume.\n' "$GREEN" "$RESET"
else
  warn "Zweiter Abruf meldet \"$SECOND_STATUS\" statt HIT - der erste konnte nichts"
  warn "ablegen. Wahrscheinlichste Ursache: das Volume wurde angelegt, bevor das"
  warn "Image den Ordner enthielt - dann gehört es dauerhaft root."
  note "Reparatur: Volume in Dokploy entfernen, im Panel unter"
  note "Docker → Volumes das Volume \"$VOLUME_NAME\" löschen, Stage 2 wiederholen."
  exit 1
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Persistenz über ein Deployment beweisen"
say "Noch ein Deployment, danach zwei Abrufe: die zuvor gecachte Variante"
say "(w=$PROBE_WIDTH) muss HIT melden, eine nie abgerufene (w=$CONTROL_WIDTH) muss MISS melden."
say "Die Gegenprobe gehört dazu: ohne sie wäre ein HIT auch damit erklärbar,"
say "dass gar kein neuer Container läuft."
printf '\n'
confirm "Zweites Deployment auslösen?" || { warn "Ohne das ist die Persistenz nicht belegt."; exit 0; }

deploy_and_wait "Wizard image-cache-proof $$" "Persistenznachweis Image-Cache (#24)"

printf '\n'
read -r KEPT_CODE KEPT_STATUS <<<"$(probe "$PROBE_WIDTH")"
printf '  zuvor gecacht (w=%s): HTTP %s, x-nextjs-cache: %s\n' "$PROBE_WIDTH" "$KEPT_CODE" "$KEPT_STATUS"
read -r CTRL_CODE CTRL_STATUS <<<"$(probe "$CONTROL_WIDTH")"
printf '  Gegenprobe    (w=%s): HTTP %s, x-nextjs-cache: %s\n' "$CONTROL_WIDTH" "$CTRL_CODE" "$CTRL_STATUS"
printf '\n'
if [[ "$KEPT_CODE" != "200" || "$CTRL_CODE" != "200" ]]; then
  warn "Kein HTTP 200 - Prüfung wertlos."; exit 1
fi
if [[ "$CTRL_STATUS" != "MISS" ]]; then
  warn "Die Gegenprobe meldet \"$CTRL_STATUS\" statt MISS. Damit belegt ein HIT oben"
  warn "nichts - entweder war w=$CONTROL_WIDTH schon im Cache, oder es antwortet"
  warn "eine Zwischenschicht statt des Optimizers."
  note "Mit einer anderen unbenutzten Breite erneut prüfen: CONTROL_WIDTH=32 $0"
  exit 1
fi
if [[ "$KEPT_STATUS" == "HIT" ]]; then
  printf '  %s✓%s Der Cache hat das Deployment überlebt.\n' "$GREEN" "$RESET"
else
  warn "Die zuvor gecachte Variante meldet \"$KEPT_STATUS\" - der Cache überlebt das"
  warn "Deployment nicht."
  note "Prüfen: hängt das Volume wirklich an $MOUNT_PATH (Stage 2), und wurde"
  note "es angelegt, nachdem das Image den Ordner mitbrachte?"
  exit 1
fi

finish
note "Volume $VOLUME_NAME an $MOUNT_PATH - reiner Cache."
note "Löschen ist gefahrlos: es kostet einmalig Rechenzeit, keine Daten."
